// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/Accordion.vue')['default']
    CurveLine: typeof import('./src/components/CurveLine.vue')['default']
    DisplayBreviaryBox: typeof import('./src/components/DisplayBreviaryBox.vue')['default']
    DisplayRotograph: typeof import('./src/components/DisplayRotograph.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElLink: typeof import('element-plus/es')['ElLink']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IndicatorProgress: typeof import('./src/components/IndicatorProgress.vue')['default']
    Logo: typeof import('./src/components/logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shuffling: typeof import('./src/components/Shuffling.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
