export type { IFood } from './food'
export type { IShufflingImg } from './Shuffling'
export type { IHomeScenic, IHomeFestival, IHomeItinerary } from './home'
export type { IWay, IWayItem } from './way'
export type { IRotograph, IScenic } from './scenic'
